### ISSUE TITLE
Hi, could I get help from you?

### ISSUE THREAD

**Issue by poweihuang17** [jaidTw/linux-kvm-arm-instrumentation#1]
Hi Jesse,
I'm Po-wei Huang. Also taking course now.
Could I get some help from you for this hw? I accidentally found your code on github, and I didn't get the chance to get help from TA.
Could I ask you how to identify MEM fault and I/O fault?
Thanks,

**Comment by jaidTw** [comment]
Hi, I'm not sure my implementation were correct, but welcome to discuss with me :)

**Comment by jaidTw** [comment]
According to the manual, I think there's only data and instructions abort are related to IO and mem fault, and both of them are using the same handler `kvm_handle_guest_abort()`, and the comment of the handler tells that there are two type of faults, which is IO memory fault and main memory fault,.
I guess the `if` section which calls the `io_mem_abort()`  is for dealing with MMIO fault, and the statements below calls the `user_mem_abort` is for mem fault

**Comment by poweihuang17** [comment]
Hi, JaidTw. Thank you. We are studying what you said. But we found that for mem, the trap count is pretty small.

**Comment by jaidTw** [comment]
Hi, You can compare your trap count to the picture provide by TA in the HW description.
The mem count in our experiments is ~ 23K, which is almost same as the picture.

**Comment by poweihuang17** [comment]
Yes, I know. But when you execute mem, did you get any additional memory trap?

**Comment by jaidTw** [comment]
There were some, but stop growing soon, we guest that not every memory falut will trap to EL2, you can refer to the MMU faults and Virtual Memory section in the manual.

**Comment by poweihuang17** [comment]
OK. Thank you!
